-- noita.lua
-- Neovim colorscheme inspired by Noita.

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "noita"
vim.o.background = "dark"
vim.o.termguicolors = true

-- Reload palette edits with :colorscheme noita.
package.loaded["noita.palette"] = nil
local p = require("noita.palette")

-- ── Highlight table ─────────────────────────────────────────────────────────
-- String values are treated as links in the apply loop below.
local hl = {

  -- ── Base Vim ──────────────────────────────────────────────────────────────
  Normal = { fg = p.bone, bg = p.mines },
  NormalNC = "Normal",
  NormalFloat = "Normal",
  FloatBorder = { fg = p.tablet, bg = p.mines },
  FloatTitle = { fg = p.tele, bg = p.mines, bold = true },
  ColorColumn = { bg = p.wasteland },
  Conceal = { fg = p.water },
  Cursor = { fg = p.void, bg = p.bone },
  lCursor = "Cursor",
  CursorIM = "Cursor",
  TermCursor = { fg = p.void, bg = p.bone },
  TermCursorNC = { fg = p.void, bg = p.water },
  CursorLine = { bg = p.wasteland },
  CursorColumn = { bg = p.wasteland },
  CursorLineNr = { fg = p.tablet, bold = true },
  Directory = { fg = p.tablet },
  DiffAdd = { bg = p.jungle, },
  DiffChange = { bg = p.wasteland },
  DiffDelete = { bg = p.hell },
  DiffText = { bg = p.base, bold = true },
  EndOfBuffer = { fg = p.mines },
  ErrorMsg = { fg = p.blood, bold = true },
  VertSplit = "WinSeparator",
  WinSeparator = { fg = p.muted, bg = p.mines },
  Folded = { fg = p.water, bg = p.pits, italic = true },
  FoldColumn = { fg = p.water, bg = p.mines },
  SignColumn = { fg = p.bone, bg = p.mines },
  IncSearch = { fg = p.void, bg = p.lava, bold = true },
  CurSearch = { fg = p.void, bg = p.glyph, bold = true },
  YankFlash = { fg = p.void, bg = p.ice },
  Substitute = { fg = p.void, bg = p.blood, bold = true },
  LineNr = { fg = p.muted },
  LineNrAbove = "LineNr",
  LineNrBelow = "LineNr",
  MatchParen = { fg = p.ambrosia, bold = true, underline = true },
  ModeMsg = { fg = p.tele, bold = true },
  MsgArea = { fg = p.bone },
  MsgSeparator = { fg = p.cloak },
  MoreMsg = { fg = p.tablet },
  NonText = { fg = p.muted },
  Pmenu = { fg = p.bone, bg = p.mines, blend = 0 },
  PmenuSel = { fg = p.void, bg = p.tele, blend = 0 },
  PmenuSbar = { bg = p.mines },
  PmenuThumb = { bg = p.cloak },
  PmenuKind = { fg = p.mana, bg = p.mines, blend = 0 },
  PmenuKindSel = "PmenuSel",
  PmenuExtra = { fg = p.water, bg = p.mines, blend = 0 },
  PmenuExtraSel = "PmenuSel",
  PmenuMatch = { fg = p.ambrosia, bold = true },
  PmenuMatchSel = { fg = p.void, bg = p.tele, bold = true, underline = true, blend = 0 },
  Question = { fg = p.tele },
  QuickFixLine = { bg = p.wasteland },
  Search = { fg = p.void, bg = p.ambrosia, bold = true },
  SpecialKey = { fg = p.water },
  SpellBad = { undercurl = true, sp = p.blood },
  SpellCap = { undercurl = true, sp = p.lava },
  SpellLocal = { undercurl = true, sp = p.tablet },
  SpellRare = { undercurl = true, sp = p.gold },
  StatusLine = { fg = p.bone, bg = p.mines },
  StatusLineNC = { fg = p.water, bg = p.mines },
  TabLine = { fg = p.water, bg = p.mines },
  TabLineFill = { bg = p.mines },
  TabLineSel = { fg = p.bone, bg = p.cloak },
  Title = { fg = p.tele, bold = true },
  Visual = { bg = p.base },
  VisualNOS = { bg = p.base },
  WarningMsg = { fg = p.lava, bold = true },
  Whitespace = { fg = p.cloak },
  WildMenu = { fg = p.bone, bg = p.cloak },
  WinBar = { fg = p.bone, bg = p.mines },
  WinBarNC = { fg = p.water, bg = p.mines },

  -- ── Syntax ────────────────────────────────────────────────────────────────
  Comment = { fg = p.tablet, italic = true },
  Constant = { fg = p.ambrosia },
  String = { fg = p.sludge },
  Character = "String",
  Number = "Constant",
  Boolean = "Constant",
  Float = "Number",
  Identifier = { fg = p.bone },
  Function = { fg = p.fungus },
  Statement = "Keyword",
  Conditional = "Keyword",
  Repeat = "Keyword",
  Label = { fg = p.tele },
  Operator = { fg = p.water },
  Keyword = { fg = p.portal },
  Exception = { fg = p.blood },
  PreProc = "Keyword",
  Include = "PreProc",
  Define = "PreProc",
  Macro = "Constant",
  PreCondit = "PreProc",
  Type = { fg = p.mana },
  StorageClass = "Type",
  Structure = "Type",
  Typedef = "Type",
  Special = { fg = p.gold },
  SpecialChar = { fg = p.blood },
  Tag = { fg = p.tele },
  Delimiter = { fg = p.water },
  SpecialComment = "Comment",
  Debug = { fg = p.lava },
  Underlined = { underline = true },
  Ignore = { fg = p.water },
  Error = { fg = p.blood, bold = true },
  Todo = { fg = p.void, bg = p.tele, bold = true },

  -- ── Treesitter ────────────────────────────────────────────────────────────
  ["@variable"] = "Identifier",
  ["@variable.builtin"] = "Constant",
  ["@variable.parameter"] = "Identifier",
  ["@variable.member"] = "@property",
  ["@constant"] = "Constant",
  ["@constant.builtin"] = "Constant",
  ["@constant.macro"] = "Macro",
  ["@module"] = { fg = p.ambrosia },
  ["@module.builtin"] = "@module",
  ["@label"] = "Label",
  ["@string"] = "String",
  ["@string.documentation"] = { fg = p.sludge, italic = true },
  ["@string.regexp"] = { fg = p.lava },
  ["@string.escape"] = "SpecialChar",
  ["@string.special"] = { fg = p.ambrosia },
  ["@string.special.symbol"] = { fg = p.ambrosia },
  ["@string.special.url"] = { fg = p.mana, underline = true },
  ["@character"] = "Character",
  ["@character.special"] = "SpecialChar",
  ["@number"] = "Number",
  ["@number.float"] = "Float",
  ["@boolean"] = "Boolean",
  ["@function"] = "Function",
  ["@function.builtin"] = "Function",
  ["@function.call"] = "Function",
  ["@function.macro"] = "Function",
  ["@function.method"] = "Function",
  ["@function.method.call"] = "Function",
  ["@constructor"] = "Type",
  ["@operator"] = "Operator",
  ["@keyword"] = "Keyword",
  ["@keyword.coroutine"] = "Keyword",
  ["@keyword.function"] = "Keyword",
  ["@keyword.operator"] = "Operator",
  ["@keyword.import"] = "Include",
  ["@keyword.storage"] = "StorageClass",
  ["@keyword.repeat"] = "Repeat",
  ["@keyword.return"] = "Keyword",
  ["@keyword.debug"] = "Debug",
  ["@keyword.exception"] = "Exception",
  ["@keyword.conditional"] = "Conditional",
  ["@keyword.conditional.ternary"] = "Conditional",
  ["@keyword.directive"] = "PreProc",
  ["@keyword.directive.define"] = "Define",
  ["@punctuation.delimiter"] = "Delimiter",
  ["@punctuation.bracket"] = "Delimiter",
  ["@punctuation.special"] = { fg = p.gold },
  ["@comment"] = "Comment",
  ["@comment.documentation"] = "Comment",
  ["@comment.error"] = "Error",
  ["@comment.warning"] = "WarningMsg",
  ["@comment.todo"] = { fg = p.void, bg = p.tablet, bold = true },
  ["@comment.note"] = { fg = p.void, bg = p.tablet, bold = true },
  ["@type"] = "Type",
  ["@type.builtin"] = "Type",
  ["@type.definition"] = "Type",
  ["@attribute"] = { fg = p.lava },
  ["@attribute.builtin"] = { fg = p.ambrosia },
  ["@property"] = { fg = p.tele },
  ["@tag"] = "Tag",
  ["@tag.builtin"] = { fg = p.ambrosia },
  ["@tag.attribute"] = { fg = p.portal },
  ["@tag.delimiter"] = "Delimiter",
  ["@diff.plus"] = { bg = p.jungle },
  ["@diff.minus"] = { bg = p.hell, fg = p.lava },
  ["@diff.delta"] = "DiffChange",
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = p.tele, bold = true },
  ["@markup.heading.1"] = { fg = p.tele, bold = true },
  ["@markup.heading.2"] = { fg = p.tablet, bold = true },
  ["@markup.heading.3"] = { fg = p.sludge, bold = true },
  ["@markup.heading.4"] = { fg = p.gold },
  ["@markup.heading.5"] = { fg = p.water },
  ["@markup.heading.6"] = { fg = p.water },
  ["@markup.quote"] = { fg = p.tablet, italic = true },
  ["@markup.math"] = { fg = p.gold },
  ["@markup.link"] = { fg = p.tele, underline = true },
  ["@markup.link.label"] = { fg = p.tele },
  ["@markup.link.url"] = { fg = p.mana, underline = true },
  ["@markup.raw"] = { fg = p.bone },
  ["@markup.raw.block"] = { fg = p.bone },
  ["@markup.list"] = { fg = p.tele },
  ["@markup.list.checked"] = { fg = p.sludge },
  ["@markup.list.unchecked"] = { fg = p.water },

  -- ── LSP semantic tokens ───────────────────────────────────────────────────
  ["@lsp.type.class"] = "@type",
  ["@lsp.type.comment"] = "@comment",
  ["@lsp.type.decorator"] = "@attribute",
  ["@lsp.type.enum"] = "@type",
  ["@lsp.type.enumMember"] = "@constant",
  ["@lsp.type.event"] = "@type",
  ["@lsp.type.function"] = "@function",
  ["@lsp.type.interface"] = "@type",
  ["@lsp.type.keyword"] = "@keyword",
  ["@lsp.type.macro"] = "@constant.macro",
  ["@lsp.type.method"] = "@function.method",
  ["@lsp.type.modifier"] = "@keyword",
  ["@lsp.type.namespace"] = "@module",
  ["@lsp.type.number"] = "@number",
  ["@lsp.type.operator"] = "@operator",
  ["@lsp.type.parameter"] = "@variable.parameter",
  ["@lsp.type.property"] = "@property",
  ["@lsp.type.regexp"] = "@string.regexp",
  ["@lsp.type.string"] = "@string",
  ["@lsp.type.struct"] = "@type",
  ["@lsp.type.type"] = "@type",
  ["@lsp.type.typeParameter"] = "@type",
  ["@lsp.type.variable"] = "@variable",
  ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
  ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
  ["@lsp.typemod.type.defaultLibrary"] = "@type.builtin",

  -- ── Diagnostics ───────────────────────────────────────────────────────────
  DiagnosticError = { fg = p.blood },
  DiagnosticWarn = { fg = p.lava },
  DiagnosticInfo = { fg = p.tele },
  DiagnosticHint = { fg = p.tablet },
  DiagnosticOk = { fg = p.tablet },
  DiagnosticVirtualTextError = { fg = p.blood, bg = p.hell, italic = true },
  DiagnosticVirtualTextWarn = { fg = p.lava, bg = p.wasteland, italic = true },
  DiagnosticVirtualTextInfo = { fg = p.tele, bg = p.wasteland, italic = true },
  DiagnosticVirtualTextHint = { fg = p.tablet, bg = p.jungle, italic = true },
  DiagnosticVirtualTextOk = { fg = p.tablet, bg = p.jungle, italic = true },
  DiagnosticUnderlineError = { undercurl = true, sp = p.blood },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.lava },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.tele },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.tablet },
  DiagnosticUnderlineOk = { undercurl = true, sp = p.tablet },
  DiagnosticFloatingError = { fg = p.blood },
  DiagnosticFloatingWarn = { fg = p.lava },
  DiagnosticFloatingInfo = { fg = p.tele },
  DiagnosticFloatingHint = { fg = p.tablet },
  DiagnosticSignError = { fg = p.blood },
  DiagnosticSignWarn = { fg = p.lava },
  DiagnosticSignInfo = { fg = p.tele },
  DiagnosticSignHint = { fg = p.tablet },

  -- ── flash.nvim ───────────────────────────────────────────────────────────────
  FlashLabel = { fg = p.void, bg = p.tele, bold = true },
  FlashMatch = { fg = p.void, bg = p.ambrosia, bold = true },
  FlashCurrent = { fg = p.void, bg = p.lava, bold = true },
  FlashBackdrop = { fg = p.water },
  FlashPrompt = { fg = p.bone, bg = p.mines },
  FlashPromptMode = { fg = p.tele, bg = p.mines, bold = true },
  FlashCursor = "Cursor",

  -- ── gitsigns ─────────────────────────────────────────────────────────────
  GitSignsAdd = { fg = p.sludge },
  GitSignsChange = { fg = p.ambrosia },
  GitSignsDelete = { fg = p.blood },
  GitSignsAddNr = "GitSignsAdd",
  GitSignsChangeNr = "GitSignsChange",
  GitSignsDeleteNr = "GitSignsDelete",
  GitSignsAddLn = { bg = p.jungle },
  GitSignsChangeLn = { bg = p.wasteland },
  GitSignsDeleteLn = { bg = p.hell },
  GitSignsAddInline = { fg = p.void, bg = p.tablet },
  GitSignsChangeInline = { fg = p.void, bg = p.lava },
  GitSignsDeleteInline = { fg = p.void, bg = p.glyph },

  -- ── snacks.nvim ───────────────────────────────────────────────────────────
  SnacksNormal = "Normal",
  SnacksNormalNC = "Normal",
  SnacksWinBar = { fg = p.tele, bold = true },
  SnacksWinBarNC = "SnacksWinBar",
  SnacksBackdrop = { fg = p.water, bg = p.mines },
  SnacksDashboardHeader = { fg = p.sludge, bold = true },
  SnacksDashboardFooter = { fg = p.water, italic = true },
  SnacksDashboardTitle = { fg = p.tele, bold = true },
  SnacksDashboardDesc = { fg = p.bone },
  SnacksDashboardKey = { fg = p.fungus, bold = true },
  SnacksDashboardIcon = { fg = p.tablet },
  SnacksDashboardDir = { fg = p.water },
  SnacksDashboardFile = { fg = p.bone },
  SnacksDashboardSpecial = { fg = p.water },
  SnacksDashboardTerminal = { fg = p.bone },
  SnacksNotifierDebug = { fg = p.water },
  SnacksNotifierTrace = { fg = p.water },
  SnacksNotifierInfo = { fg = p.bone },
  SnacksNotifierWarn = { fg = p.lava },
  SnacksNotifierError = { fg = p.blood },
  SnacksNotifierBorderDebug = { fg = p.temple },
  SnacksNotifierBorderTrace = { fg = p.temple },
  SnacksNotifierBorderInfo = { fg = p.tele },
  SnacksNotifierBorderWarn = { fg = p.lava },
  SnacksNotifierBorderError = { fg = p.blood },
  SnacksNotifierTitleDebug = { fg = p.water, bold = true },
  SnacksNotifierTitleTrace = { fg = p.water, bold = true },
  SnacksNotifierTitleInfo = { fg = p.tele, bold = true },
  SnacksNotifierTitleWarn = { fg = p.lava, bold = true },
  SnacksNotifierTitleError = { fg = p.blood, bold = true },
  SnacksNotifierIconDebug = { fg = p.water },
  SnacksNotifierIconTrace = { fg = p.water },
  SnacksNotifierIconInfo = { fg = p.tele },
  SnacksNotifierIconWarn = { fg = p.lava },
  SnacksNotifierIconError = { fg = p.blood },
  SnacksNotifierFooterDebug = { fg = p.water },
  SnacksNotifierFooterTrace = { fg = p.water },
  SnacksNotifierFooterInfo = { fg = p.tele },
  SnacksNotifierFooterWarn = { fg = p.lava },
  SnacksNotifierFooterError = { fg = p.blood },
  SnacksIndent = { fg = p.cloak },
  SnacksIndentScope = { fg = p.water },
  SnacksPicker = "NormalFloat",
  SnacksPickerBorder = "FloatBorder",
  SnacksPickerInput = "NormalFloat",
  SnacksPickerPrompt = { fg = p.tele },
  SnacksPickerDir = { fg = p.water },
  SnacksPickerFile = { fg = p.bone },
  SnacksPickerMatch = { fg = p.ambrosia, bold = true },
  SnacksPickerSelected = { fg = p.fungus },
  SnacksPickerToggle = { fg = p.tele },
  SnacksPickerInputBorder = { fg = p.tablet },
  SnacksPickerInputTitle = { fg = p.tele, bold = true },
  SnacksPickerListTitle = { fg = p.bone, bold = true },
  SnacksPickerPreviewTitle = { fg = p.water, bold = true },
  SnacksInputBorder = { fg = p.tablet },
  SnacksInputTitle = { fg = p.tele, bold = true },

  -- ── noice.nvim ────────────────────────────────────────────────────────────
  NoiceCmdline = "NormalFloat",
  NoiceCmdlineIcon = { fg = p.tele },
  NoiceCmdlineIconSearch = { fg = p.ambrosia },
  NoiceCmdlinePopup = "NormalFloat",
  NoiceCmdlinePopupBorder = { fg = p.tablet },
  NoiceCmdlinePopupBorderSearch = { fg = p.ambrosia },
  NoiceCmdlinePopupTitle = { fg = p.tele, bold = true },
  NoicePopup = "NormalFloat",
  NoicePopupBorder = { fg = p.tablet },
  NoiceConfirm = "NormalFloat",
  NoiceConfirmBorder = { fg = p.tablet },
  NoiceMini = { fg = p.bone, bg = p.mines },
  NoiceFormatProgressDone = { fg = p.void, bg = p.tablet },
  NoiceFormatProgressTodo = { fg = p.water, bg = p.mines },
  NoiceLspProgressSpinner = { fg = p.tele },
  NoiceLspProgressTitle = { fg = p.bone },
  NoiceLspProgressClient = { fg = p.water },

  -- ── which-key ─────────────────────────────────────────────────────────────
  WhichKey = { fg = p.fungus },
  WhichKeyGroup = { fg = p.tele },
  WhichKeyDesc = { fg = p.bone },
  WhichKeySeparator = { fg = p.water },
  WhichKeyBorder = { fg = p.tablet },
  WhichKeyNormal = "NormalFloat",
  WhichKeyValue = { fg = p.water },

}

-- ── Terminal colors ──────────────────────────────────────────────────────────
vim.g.terminal_color_0  = p.void     -- black
vim.g.terminal_color_1  = p.glyph    -- red
vim.g.terminal_color_2  = p.sludge   -- green
vim.g.terminal_color_3  = p.ambrosia -- yellow
vim.g.terminal_color_4  = p.mana     -- blue
vim.g.terminal_color_5  = p.fungus   -- magenta
vim.g.terminal_color_6  = p.tele     -- cyan
vim.g.terminal_color_7  = p.bone     -- white
vim.g.terminal_color_8  = p.water    -- bright black
vim.g.terminal_color_9  = p.blood    -- bright red
vim.g.terminal_color_10 = p.tablet   -- bright green
vim.g.terminal_color_11 = p.gold     -- bright yellow
vim.g.terminal_color_12 = p.ice      -- bright blue
vim.g.terminal_color_13 = p.lava     -- bright magenta
vim.g.terminal_color_14 = p.portal   -- bright cyan
vim.g.terminal_color_15 = p.bone     -- bright white

-- ── Apply ────────────────────────────────────────────────────────────────────
for group, spec in pairs(hl) do
  vim.api.nvim_set_hl(0, group, type(spec) == "string" and { link = spec } or spec)
end
