source "~/.config/tmux/conf/options.tmux"
source "~/.config/tmux/conf/keybinds.tmux"
source "~/.config/tmux/conf/status.tmux"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_action 'copy-pipe-and-cancel'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'decodingintuition/tmux-flash'

run '~/.config/tmux/plugins/tpm/tpm'
